name: adguardhome

services:
  agh:
    container_name: agh
    hostname: agh
    image: sb/adguard-unbound
    restart: unless-stopped
    ports:
      # plain DNS
      # - 6553:53/tcp
      # - 6553:53/udp
      # add if you intend to use AdGuard Home as a DHCP server
      # - 67:67/udp
      # - 68:68/tcp
      # - 68:68/udp
      # add if you are going to use AdGuard Home's admin panel as well as run AdGuard Home as an HTTPS/DNS-over-HTTPS server
      # - 8002:80/tcp
      - 6443:443/tcp
      - 6443:443/udp
      # disable after first setup
      # - 3000:3000/tcp
      # add if you are going to run AdGuard Home as a DNS-over-TLS server
      - 853:853/tcp
      # add if you are going to run AdGuard Home as a DNS-over-QUIC server.
      - 853:853/udp
      # add if you are going to enable unbound access on local server
      #- 5053:5053/tcp
      #- 5053:5053/udp
      # add if you are going to run AdGuard Home as a DNSCrypt server.
      #- 5443:5443/tcp
      #- 5443:5443/udp
      # debugging profiles
      #- 6060:6060/tcp

    # Volumes store your data between container upgrades
    volumes:
      # adguardhome container work directory
      - ./work:/opt/adguardhome/work
      # adguardhome container conf directory
      - ./agh-conf:/opt/adguardhome/conf
      # unbound dir with custom config
      - ./unbound-conf:/opt/unbound
      # DNSSEC key and root hints from dns-root-data package
      # not required as it is already present in the image
      # - /usr/share/dns:/usr/share/dns
      # ssl certificates for domain and subdomain
      - /home/dns/nginx/dns.example.com:/cert
    environment:
      - TZ=Europe/Kyiv
    deploy:
      resources:
        limits:
          # Number of CPU threads
          cpus: '2.00'
          # Gigabytes of memory
          memory: '4G'
    # You only need to leave one: or network_mode: or networks:
    network_mode: "bridge"
#     networks:
#       dns:
#         ipv4_address: 10.10.4.2

# networks:
#     dns:
#         driver: bridge
#         ipam:
#           config:
#             - subnet: 10.10.4.0/16
#               gateway: 10.10.4.1